# syntax=docker/dockerfile:1.7
FROM node:20-alpine AS dependencies

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --no-fund

FROM dependencies AS development

WORKDIR /app

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3002

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_BROWSER_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_BROWSER_API_URL=$NEXT_PUBLIC_BROWSER_API_URL

ARG NEXT_PUBLIC_GITHUB_URL
ARG NEXT_PUBLIC_GA4_URL
ARG NEXT_PUBLIC_POSTHOG_URL
ARG NEXT_PUBLIC_SENTRY_URL
ARG NEXT_PUBLIC_GRAFANA_URL
ARG NEXT_PUBLIC_CLOUDWATCH_URL
ARG NEXT_PUBLIC_AWS_CONSOLE_URL
ARG NEXT_PUBLIC_STRIPE_URL

ENV NEXT_PUBLIC_GITHUB_URL=$NEXT_PUBLIC_GITHUB_URL
ENV NEXT_PUBLIC_GA4_URL=$NEXT_PUBLIC_GA4_URL
ENV NEXT_PUBLIC_POSTHOG_URL=$NEXT_PUBLIC_POSTHOG_URL
ENV NEXT_PUBLIC_SENTRY_URL=$NEXT_PUBLIC_SENTRY_URL
ENV NEXT_PUBLIC_GRAFANA_URL=$NEXT_PUBLIC_GRAFANA_URL
ENV NEXT_PUBLIC_CLOUDWATCH_URL=$NEXT_PUBLIC_CLOUDWATCH_URL
ENV NEXT_PUBLIC_AWS_CONSOLE_URL=$NEXT_PUBLIC_AWS_CONSOLE_URL
ENV NEXT_PUBLIC_STRIPE_URL=$NEXT_PUBLIC_STRIPE_URL

EXPOSE 3002

CMD ["npm", "run", "dev"]

FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_BROWSER_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_BROWSER_API_URL=$NEXT_PUBLIC_BROWSER_API_URL

ARG NEXT_PUBLIC_GITHUB_URL
ARG NEXT_PUBLIC_GA4_URL
ARG NEXT_PUBLIC_POSTHOG_URL
ARG NEXT_PUBLIC_SENTRY_URL
ARG NEXT_PUBLIC_GRAFANA_URL
ARG NEXT_PUBLIC_CLOUDWATCH_URL
ARG NEXT_PUBLIC_AWS_CONSOLE_URL
ARG NEXT_PUBLIC_STRIPE_URL

ENV NEXT_PUBLIC_GITHUB_URL=$NEXT_PUBLIC_GITHUB_URL
ENV NEXT_PUBLIC_GA4_URL=$NEXT_PUBLIC_GA4_URL
ENV NEXT_PUBLIC_POSTHOG_URL=$NEXT_PUBLIC_POSTHOG_URL
ENV NEXT_PUBLIC_SENTRY_URL=$NEXT_PUBLIC_SENTRY_URL
ENV NEXT_PUBLIC_GRAFANA_URL=$NEXT_PUBLIC_GRAFANA_URL
ENV NEXT_PUBLIC_CLOUDWATCH_URL=$NEXT_PUBLIC_CLOUDWATCH_URL
ENV NEXT_PUBLIC_AWS_CONSOLE_URL=$NEXT_PUBLIC_AWS_CONSOLE_URL
ENV NEXT_PUBLIC_STRIPE_URL=$NEXT_PUBLIC_STRIPE_URL

ARG NEXT_PUBLIC_SENTRY_DSN
ARG SENTRY_ENVIRONMENT
ARG SENTRY_TRACES_SAMPLE_RATE

ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT
ENV SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3002

RUN addgroup --system --gid 1001 qivro \
    && adduser --system --uid 1001 --ingroup qivro qivro

COPY --from=builder --chown=qivro:qivro /app/package*.json ./
COPY --from=builder --chown=qivro:qivro /app/node_modules ./node_modules
COPY --from=builder --chown=qivro:qivro /app/.next ./.next
COPY --from=builder --chown=qivro:qivro /app/next.config.ts ./next.config.ts

USER qivro

EXPOSE 3002

CMD ["npm", "run", "start"]
